### ISSUE TITLE
Tidying the pipeline

### ISSUE THREAD

**Issue by anyaferguson** [The-Strategy-Unit/nhp_royalliverpool_newsite#114]
I’ve noticed some bits in the pipeline could be tidied up and standardised. For example, we have objects with site_name as the suffix and others with site_code and there’s targets that could be written in a loop to make it easier to read and update. So I’m creating a new branch to tidy up bits today and will flag any big changes here.

**Comment by anyaferguson** [comment]
In PR #116 the following updates to the pipeline were made:

- There are a few minor changes like changing comments or creating headers.
- For creating the maps `tarchetypes::tar_map()` was used. So instead of creating a target for each site, there is one target that loops over to create an object for each site. This was used previously to create the standard charts.
- Plots and maps that had the suffix `_site_name` have been renamed with the suffix `_site_code` to match the naming of the CIA objects. 
- In the function `cia_analysis()`, the arguments `switch_month` and `site` have been removed and instead are pulled from the object `hospitals` using the `organisation` already supplied. 

I think we could use `tarchetypes::tar_map()` for `cia_analysis()`, iterating over `organisation` and `prior_sd`, but I wasn't too sure of how `prior_sd` is chosen. @SarahLucas3 it would be good if we could look at this together and see if we could use `tarchetypes::tar_map()` here instead to tidy the script up a bit more.

@SarahLucas3, @DandyOoh I'll leave this issue open for now in case other bits come up, but please pull the changes from main when you can.

**Comment by anyaferguson** [comment]
For more info about `tarchetypes::tar_map()` I found the following useful:

- https://docs.ropensci.org/tarchetypes/reference/tar_map.html
- https://books.ropensci.org/targets/static.html

I'm also happy to talk it through if you have questions.

**Comment by DandyOoh** [comment]
Putting here as closed previous issue...

@SarahLucas3 i've added the elective:nonelective ratio variable to the controls. It's included in the rank of ranks so may have changed the CIA. If you check and it's thrown things out of whack i will wind back and just add as an extra variable to the matches table rather than include in ranks. Interesting to see what happens.

**Comment by DandyOoh** [comment]
All done
